routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->to('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => 'auth'], function () {
    Route::resource('outlets', 'OutletController');
    Route::resource('users', 'UserController');
    Route::resource('transactions', 'TransactionController');
    Route::resource('inventories', 'InventoryController');
    Route::prefix('inventory')->group(function () {
        Route::resource('products', 'ProductController');
        Route::resource('categories', 'CategoryController');
    });
});

Route::get('/invoice/{id}', 'TransactionController@invoice');

app/Http/Controllers/API/TransactionController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Transaction;
use Illuminate\Http\Request;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $transactions = Transaction::all();
        $data = [
            'status' => 'success',
            'data' => $transactions
        ];
        return response()->json($data, 200);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function show(Transaction $transaction)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Transaction $transaction)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaction $transaction)
    {
        //
    }
}

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Transaction;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\Auth;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $header_table = [
            'id' => 'ID',
            'invoice' => 'Invoice',
            'final_price' => 'Harga',
            'cash' => 'Uang Bayar',
            'change' => 'Kembalian',
            'action' => 'Aksi'
        ];
        if (request()->ajax()) {
            $transactions = Transaction::all(['id', 'final_price', 'invoice', 'cash', 'change']);
            return DataTables::of($transactions)->editColumn('change', function ($product) {
                return "Rp. " . number_format($product->change, 0, ',', '.');
            })->editColumn('final_price', function ($product) {
                return "Rp. " . number_format($product->final_price, 0, ',', '.');
            })->editColumn('cash', function ($product) {
                return "Rp. " . number_format($product->cash, 0, ',', '.');
            })->addColumn('action', function ($data) {
                $show = '<button onclick="show_detail_transaction(' . $data->id . ')" class="btn btn-sm btn-primary"><i class="fa fa-info"></i> Detail</button>';
                $invoice = '<button onclick="invoice(' . $data->id . ')" class="btn btn-sm btn-warning"><i class="fa fa-info"></i> Invoice</button>';
                $action = '<div class="btn-group" role="group" aria-label="Basic example">' . $show . $invoice . '</div>';
                return $action;
            })->rawColumns(['action'])->make(true);
        }
        $products = Product::all();
        return view('transaction.index', compact('header_table', 'products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'invoice' => 'required',
            'final_price' => 'required|gte:0',
            'cash' => 'required|gte:final_price',
            'change' => 'required',
            'list_barang' => 'required'
        ]);
        $list_barang =  json_decode($request->list_barang);
        $iput_transaksi = $request->except('list_barang');
        $iput_transaksi['invoice'] = $request->invoice . Transaction::max('id');
        $iput_transaksi['user_id'] = Auth::user()->id;
        $transaction = Transaction::create($iput_transaksi);
        foreach ($list_barang as $barang) {
            $product = Product::find($barang->id);
            $product->qty = $product->qty - $barang->qty;
            $product->save();
            $transaction->products()->attach($barang->id, ['qty' => $barang->qty, 'final_price' => $barang->final_price]);
        }
        return response()->json(['message' => 'Berhasil Menambahkan Transaksi'], 201);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function show(Transaction $transaction)
    {
        $products = $transaction->load('products')->products;
        foreach ($products as $product) {
            $product->price = number_format($product->price, 0, ',', '.');
            $product->final_price = number_format($product->price, 0, ',', '.');
        }
        return $products;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function edit(Transaction $transaction)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Transaction $transaction)
    {
        //
    }

    public function invoice($id)
    {
        $transaction = Transaction::find($id);
        $products = $transaction->load('products')->products;
        return view('invoice.index', compact('transaction', 'products'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaction $transaction)
    {
        //
    }
}

resources/views/transaction/form.blade.php
<div class="col-lg-4 mt-0">
    <div class="card">
        <div class="card-header">
            Data Transakasi
        </div>
        <div class="card-body">
            <div class="col-sm-12">
                <div class="form-group">
                    {!! Form::label('invoice', 'No Invoice', ['class'=>'placeholder']) !!}
                    {!! Form::input('text', 'invoice', "INV-".date('YmdHis'), ['class' => 'form-control
                    form-control-sm', 'disabled']) !!}
                </div>
            </div>
            
            <div class="col-sm-12">
                <div class="form-group">
                    {!! Form::label('final_price', 'Harga Ahir', ['class'=>'placeholder']) !!}
                    {!! Form::input('number', 'final_price', 0, ['disabled','class' => 'form-control
                    form-control-sm']) !!}
                </div>
            </div>

            <div class="col-sm-12">
                <div class="form-group">
                    {!! Form::label('cash', 'Uang Bayar', ['class'=>'placeholder']) !!}
                    {!! Form::number('cash', 0, ['class' => 'form-control form-control-sm', 'rows' => "3"]) !!}
                </div>
            </div>
            <div class="col-sm-12">
                <div class="form-group">
                    {!! Form::label('change', 'Uang Kembalian', ['class'=>'placeholder']) !!}
                    {!! Form::text('change', 0, ['class' => 'form-control form-control-sm', 'readonly']) !!}
                </div>
            </div>
            <div class="col-sm-12">
                <div class="form-group">
                    {!! Form::label('note', 'Catatan Transaksi', ['class'=>'placeholder']) !!}
                    {!! Form::textarea('note', null, ['class' => 'form-control form-control-sm', 'rows' => "3"]) !!}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-8">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-5">
                    <div class="form-group">
                        {!! Form::label('product', 'Poduk ', ['class'=>'placeholder']) !!}
                        <select class="form-control" style="width: 100%;" name="product" id="product">
                            @foreach($products as $product)
                            <option value="{{$product->id}}" data-price="{{$product->price}}"
                                data-qty="{{$product->qty}}">{{$product->name}}
                            </option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        {!! Form::label('jumlah', 'Jumlah ', ['class'=>'placeholder']) !!}
                        {!! Form::number('jumlah', null, ['class' => 'form-control', 'rows' => "3", 'max' =>
                        '2']) !!}
                    </div>
                </div>
                <div class="col-md-3">
                    <input type="button" onclick="addbarang()" class="btn btn-primary btn-full" value="Tambah"
                        style="margin-top: 40px;">
                </div>
            </div>

            <table class="table" style="width: 100%" id="table_barang">
                <thead>
                    <th>Nama Barang</th>
                    <th>Jumlah</th>
                    <th>Harga</th>
                    <th>Total</th>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>

@push('js')
<script>
    var barang = [];
    $("#product").change(function(){
        let max = $('#product').select2('data')[0].element.dataset.qty;
        $("#jumlah").attr({"max":max});
    });
    $("#cash").on("input", function(){
        let total = parseInt($("#final_price").val());
        let bayar = parseInt($("#cash").val())
        console.log(bayar-total);
        $("#change").val(bayar-total);
        // alert(sisa);
    })
    $("#close_btn").click(function(){
        barang = [];
        refresh_table();
    });
    function save_trans(){
        let form = new FormData();
        form.append('invoice', $("#invoice").val());
        form.append('final_price', $("#final_price").val())
        form.append('cash', $("#cash").val())
        form.append('change', $("#change").val())
        form.append('note', $("#note").val())
        form.append('list_barang', JSON.stringify(barang));
        $.ajax({
            url: method == 'POST' ? url : url + '/' + edited_id,
            type: 'POST',
            data: form,
            processData: false,
            contentType: false,
            dataType: "JSON",
            beforeSend: function () {
                if(method != 'POST'){
                    form.append('_method', 'PATCH');
                }
            },
            success: function (data) {
                $("#modal_form").modal('hide');
                swal("Pesan", data.message, {
						icon : "success",
						buttons: {
							confirm: {
								className : 'btn btn-success'
							}
						},
				});
                reload_table()
                },
            error: function(xhr, error, errorThrown){
                console.log(barang);
                if (xhr.status == 422) {
                    let message = xhr.responseJSON.message;
                    let errors = xhr.responseJSON.errors;
                    swal('Error', 'Data Tidak Valid \nPastikan Data Barang Tidak Kosong', {
                        icon: 'error',
                        buttons: {
                            confirm:{
                                className: 'btn btn-info'
                            }
                        }
                    });
                }
            }
            });
        }
        class Product{
            constructor(id, name, qty,price, final_price)
            {
                this.id = id;
                this.name= name;
                this.qty= qty;
                this.price = price;
                this.final_price = final_price;
            }
        }
        var tablebarang = $("#table_barang").dataTable({
            data: barang,
            theme: 'bootstrap',
            columns:[
                {title: 'Nama Barang', data:'name'},
                {title: 'Jumlah', data:'qty'},
                {title: 'Harga', data:'price'},
                {title: 'Total', data:'final_price'},
            ],
            pageLength: 3,
        });
        function refresh_table(){
            tablebarang.fnClearTable();
            barang.forEach(function (val) {
                tablebarang.fnAddData(val);
            });
        }
        function addbarang(){
            let product_id = $("#product").val();
            let product_qty = parseInt($("#jumlah").val());
            if(product_qty < 1 || Number.isNaN(product_qty)){
                swal("Pesan", "Jumlah Barang Tidak Boleh Kurang dari 1", {
                    icon: "warning",
                    buttons:{
                        confirm:{
                            className : 'btn btn-success'
                        }
                    }
                });
            }
            else{
                let name = $('#product').select2('data')[0]['text'];
                let price = $('#product').select2('data')[0].element.dataset.price;
                let max = $('#product').select2('data')[0].element.dataset.qty;
                if(parseInt(max) < product_qty){
                    swal("Pesan", "Jumlah Barang Tidak Boleh Lebih dari "+max, {
                    icon: "warning",
                    buttons:{
                        confirm:{
                            className : 'btn btn-warning'
                        }
                    }
                    });
                    return;
                }

                let product = new Product(product_id, name, product_qty, price, parseInt(price) * parseInt(product_qty));
                let item = barang.find(item => item.id == product_id);
                if(item === undefined){
                    barang.push(product);
                    tablebarang.fnAddData(
                        product
                    );
                }else{
                    item.qty = parseInt(item.qty) + parseInt(product_qty);
                    item.final_price = item.qty * item.price;
                    refresh_table();
                }
            }
            let total_harga = barang.map(item => item.final_price)
                                .reduce((prev, curr) => prev + curr, 0);
            $("#final_price").val(total_harga);
            let total = parseInt($("#final_price").val());
        let bayar = parseInt($("#cash").val())
        console.log(bayar-total);
        $("#change").val(bayar-total);
        }
</script>
@endpush

resources/views/transaction/index.blade.php
@extends('layouts.app')
@section('title', 'Transaki')
@section('content')
<x-data-table title="Transaksi" :header="$header_table" resource="transactions">
    @include('transaction.form')
</x-data-table>
<div class="modal fade bd-example-modal-lg" id="modal_detail" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <table class="table" style="width: 100%" id="table_detail">
                    <thead>
                        <th>Nama Barang</th>
                        <th>Jumlah</th>
                        <th>Harga</th>
                        <th>Harga Total</th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>

            <div class="modal-footer border-0">
                <button type="button" class="btn btn-danger" data-dismiss="modal" id="close_btn">Close</button>
            </div>
        </div>
    </div>
</div>
@endsection

@push('css')
<style>
    #modal_form .modal-dialog {
        width: 100%;
        height: 100%;
        padding: 0;
        margin: 0;
    }

    #modal_form .modal-content {
        height: 100%;
        border-radius: 0;
        color: #333;
        overflow: auto;
    }

    #modal_form .close {
        color: black ! important;
        opacity: 1.0;
    }

    @media (min-width: 992px) {
        #modal_form .modal-lg {
            max-width: 100%;
        }
    }

    @media (min-width: 576px) {
        #modal_form .modal-lg {
            max-width: 100%;
        }
    }
</style>
@endpush

@push('js')
<script>
    var barang = [];
    var table_detail = $("#table_detail").dataTable({
                    data:barang,
                    theme: 'bootstrap',
                    columns:[
                        {title: 'Nama Barang', data:'name'},
                        {title: 'Jumlah', data:'qty'},
                        {title: 'Harga', data:'price'},
                        {title: 'Total', data:'final_price'},
                    ],
                });
    function invoice(id){
        let url = "{{url('invoice')}}"+'/'+id;
        window.location.href = url;
    }
    function show_detail_transaction(id){
        let url = "{{route('transactions.index')}}"+'/'+id;

        barang = []
        $.ajax({
            url: url,
            type:'GET',
            dataType: 'JSON',
            success: function(data){
                data.forEach(product => {
                    console.log(product);
                    let temp_product = new Product(product.id, product.name, product.pivot.qty,"Rp. "+ product.price, "Rp. "+ product.pivot.final_price);
                    barang.push(temp_product);
                });
                table_detail.fnClearTable();
                barang.forEach(function (val) {
                    table_detail.fnAddData(val);
                });
                $("#modal_detail").modal('show');
            }

        })
    }
</script>
@endpush